//
//  ShareViewController.swift
//  RNShareMenu
//
//  DO NOT EDIT THIS FILE. IT WILL BE OVERRIDEN BY NPM OR YARN.
//
//  Created by Gustavo Parreira on 26/07/2020.
//
//  Modified by Veselin Stoyanov on 17/04/2021.

import Foundation
import MobileCoreServices
import UIKit
import Social
import RNShareMenu

class ShareViewController: SLComposeServiceViewController {
  var hostAppId: String?
  var hostAppUrlScheme: String?
  var sharedItems: [Any] = []
  
  override func viewDidLoad() {
    super.viewDidLoad()
    
    if let hostAppId = Bundle.main.object(forInfoDictionaryKey: HOST_APP_IDENTIFIER_INFO_PLIST_KEY) as? String {
      self.hostAppId = hostAppId
    } else {
      print("Error: \(NO_INFO_PLIST_INDENTIFIER_ERROR)")
    }
    
    if let hostAppUrlScheme = Bundle.main.object(forInfoDictionaryKey: HOST_URL_SCHEME_INFO_PLIST_KEY) as? String {
      self.hostAppUrlScheme = hostAppUrlScheme
    } else {
      print("Error: \(NO_INFO_PLIST_URL_SCHEME_ERROR)")
    }
  }

    override func isContentValid() -> Bool {
        // Do validation of contentText and/or NSExtensionContext attachments here
        return true
    }

    override func didSelectPost() {
        // This is called after the user selects Post. Do the upload of contentText and/or NSExtensionContext attachments.
      guard let items = extensionContext?.inputItems as? [NSExtensionItem] else {
        cancelRequest()
        return
      }

      handlePost(items)
    }

    override func configurationItems() -> [Any]! {
        // To add configuration options via table cells at the bottom of the sheet, return an array of SLComposeSheetConfigurationItem here.
        return []
    }

  func handlePost(_ items: [NSExtensionItem], extraData: [String:Any]? = nil) {
    DispatchQueue.global().async {
      guard let hostAppId = self.hostAppId else {
        self.exit(withError: NO_INFO_PLIST_INDENTIFIER_ERROR)
        return
      }
      guard let userDefaults = UserDefaults(suiteName: "group.\(hostAppId)") else {
        self.exit(withError: NO_APP_GROUP_ERROR)
        return
      }

      if let data = extraData {
        self.storeExtraData(data)
      } else {
        self.removeExtraData()
      }

      let semaphore = DispatchSemaphore(value: 0)
      var results: [Any] = []

      for item in items {
        guard let attachments = item.attachments else {
          self.cancelRequest()
          return
        }

        for provider in attachments {
          if provider.isText {
            self.storeText(withProvider: provider, semaphore)
          } else if provider.isURL {
            self.storeUrl(withProvider: provider, semaphore)
          } else if provider.isImage || provider.isData {
            self.storeFile(withProvider: provider, semaphore)
          } else {
            print("Warning: Unsupported provider type, treating as file")
            self.storeFile(withProvider: provider, semaphore)
          }

          semaphore.wait()
        }
      }

      userDefaults.set(self.sharedItems,
                       forKey: USER_DEFAULTS_KEY)
      userDefaults.synchronize()

      self.openHostApp()
    }
  }

  func storeExtraData(_ data: [String:Any]) {
    guard let hostAppId = self.hostAppId else {
      print("Error: \(NO_INFO_PLIST_INDENTIFIER_ERROR)")
      return
    }
    guard let userDefaults = UserDefaults(suiteName: "group.\(hostAppId)") else {
      print("Error: \(NO_APP_GROUP_ERROR)")
      return
    }
    userDefaults.set(data, forKey: USER_DEFAULTS_EXTRA_DATA_KEY)
    userDefaults.synchronize()
  }

  func removeExtraData() {
    guard let hostAppId = self.hostAppId else {
      print("Error: \(NO_INFO_PLIST_INDENTIFIER_ERROR)")
      return
    }
    guard let userDefaults = UserDefaults(suiteName: "group.\(hostAppId)") else {
      print("Error: \(NO_APP_GROUP_ERROR)")
      return
    }
    userDefaults.removeObject(forKey: USER_DEFAULTS_EXTRA_DATA_KEY)
    userDefaults.synchronize()
  }
  
  func storeText(withProvider provider: NSItemProvider, _ semaphore: DispatchSemaphore) {
    provider.loadItem(forTypeIdentifier: kUTTypeText as String, options: nil) { (data, error) in
      guard (error == nil) else {
        self.exit(withError: error.debugDescription)
        return
      }
      guard let text = data as? String else {
        self.exit(withError: COULD_NOT_FIND_STRING_ERROR)
        return
      }
      
      self.sharedItems.append([DATA_KEY: text, MIME_TYPE_KEY: "text/plain"])
      semaphore.signal()
    }
  }
  
  func storeUrl(withProvider provider: NSItemProvider, _ semaphore: DispatchSemaphore) {
    provider.loadItem(forTypeIdentifier: kUTTypeURL as String, options: nil) { (data, error) in
      guard (error == nil) else {
        self.exit(withError: error.debugDescription)
        return
      }
      guard let url = data as? URL else {
        self.exit(withError: COULD_NOT_FIND_URL_ERROR)
        return
      }
      
      self.sharedItems.append([DATA_KEY: url.absoluteString, MIME_TYPE_KEY: "text/plain"])
      semaphore.signal()
    }
  }
  
  func storeFile(withProvider provider: NSItemProvider, _ semaphore: DispatchSemaphore) {
    // Add debugging to see what type identifiers are available
    print("Provider registered type identifiers: \(provider.registeredTypeIdentifiers)")
    
    // Use the enhanced extension methods for better type detection
    if provider.isImage {
      print("Loading as image (from Photos app, image file, or screenshot)")
      // Use the modern loadObject method for images to properly specify expected class
      if #available(iOS 11.0, *) {
        provider.loadObject(ofClass: UIImage.self) { (image, error) in
          if let error = error {
            print("Error loading UIImage object: \(error.localizedDescription)")
            // Fallback to URL loading (which will then fallback to data loading for screenshots)
            self.loadImageAsURL(provider: provider, semaphore: semaphore)
            return
          }
          
          if let uiImage = image as? UIImage {
            print("Successfully loaded UIImage object")
            self.handleImageData(uiImage, semaphore)
          } else {
            print("Failed to cast loaded object to UIImage, trying URL fallback")
            self.loadImageAsURL(provider: provider, semaphore: semaphore)
          }
        }
      } else {
        // Fallback for iOS < 11 - go directly to data loading for screenshots
        print("iOS < 11: trying data loading approach for potential screenshots")
        self.loadImageAsData(provider: provider, semaphore: semaphore)
      }
    } else if provider.isData {
      print("Loading as data/file")
      provider.loadItem(forTypeIdentifier: kUTTypeData as String, options: nil) { (data, error) in
        if let error = error {
          print("Error loading file: \(error.localizedDescription)")
          self.exit(withError: error.localizedDescription)
          return
        }
        
        self.handleFileData(data, semaphore)
      }
    } else {
      print("Warning: Unknown provider type, attempting to load as data")
      provider.loadItem(forTypeIdentifier: kUTTypeData as String, options: nil) { (data, error) in
        if let error = error {
          print("Error loading unknown type as data: \(error.localizedDescription)")
          self.exit(withError: error.localizedDescription)
          return
        }
        
        self.handleFileData(data, semaphore)
      }
    }
  }
  
  private func loadImageAsURL(provider: NSItemProvider, semaphore: DispatchSemaphore) {
    print("Fallback: Loading image as URL")
    if #available(iOS 11.0, *) {
      provider.loadObject(ofClass: URL.self) { (url, error) in
        if let error = error {
          print("Error loading URL object: \(error.localizedDescription)")
          // Try the final fallback for screenshots
          self.loadImageAsData(provider: provider, semaphore: semaphore)
          return
        }
        
        if let imageURL = url as? URL {
          print("Successfully loaded image URL: \(imageURL.path)")
          self.handleImageData(imageURL, semaphore)
        } else {
          print("Failed to cast loaded object to URL")
          // Try the final fallback for screenshots
          self.loadImageAsData(provider: provider, semaphore: semaphore)
        }
      }
    } else {
      // iOS < 11 fallback
      provider.loadItem(forTypeIdentifier: kUTTypeImage as String, options: nil) { (data, error) in
        if let error = error {
          print("Error loading image item (iOS <11): \(error.localizedDescription)")
          self.exit(withError: error.localizedDescription)
          return
        }
        
        self.handleImageData(data, semaphore)
      }
    }
  }
  
  private func loadImageAsData(provider: NSItemProvider, semaphore: DispatchSemaphore) {
    print("Final fallback: Loading image as data (for screenshots)")
    
    // Use the generic loadItem method with public.image identifier
    // This works for screenshots that can't be coerced to UIImage or URL objects
    provider.loadItem(forTypeIdentifier: "public.image", options: nil) { (item, error) in
      if let error = error {
        print("Error loading image data: \(error.localizedDescription)")
        self.exit(withError: error.localizedDescription)
        return
      }
      
      guard let item = item else {
        print("Error: Image data item is nil")
        self.exit(withError: COULD_NOT_FIND_IMG_ERROR)
        return
      }
      
      print("Successfully loaded image data item of type: \(type(of: item))")
      
      // Handle different types that might be returned
      if let image = item as? UIImage {
        print("Item is UIImage - processing screenshot")
        self.handleImageData(image, semaphore)
      } else if let data = item as? Data {
        print("Item is Data - converting to UIImage")
        if let image = UIImage(data: data) {
          print("Successfully converted Data to UIImage")
          self.handleImageData(image, semaphore)
        } else {
          print("Error: Could not convert Data to UIImage")
          self.exit(withError: COULD_NOT_CONVERT_IMG_ERROR)
        }
      } else if let url = item as? URL {
        print("Item is URL - processing as file URL")
        self.handleImageData(url, semaphore)
      } else {
        print("Error: Unknown item type for image data: \(type(of: item))")
        self.exit(withError: COULD_NOT_FIND_IMG_ERROR)
      }
    }
  }
  
  private func handleImageData(_ data: Any?, _ semaphore: DispatchSemaphore) {
    print("Handling image data of type: \(type(of: data))")
    
    guard let data = data else {
      print("Error: Image data is nil")
      self.exit(withError: COULD_NOT_FIND_IMG_ERROR)
      return
    }
    
    var url: URL?
    
    if let image = data as? UIImage {
      print("Processing UIImage from Photos app, size: \(image.size)")
      
      // Convert UIImage to file URL - try JPEG first for better compression
      var imageData: Data?
      var fileExtension = "jpg"
      
      if let jpegData = image.jpegData(compressionQuality: 0.8) {
        imageData = jpegData
        fileExtension = "jpg"
      } else if let pngData = image.pngData() {
        imageData = pngData
        fileExtension = "png"
      }
      
      guard let finalImageData = imageData else {
        print("Error: Could not convert UIImage to data")
        self.exit(withError: COULD_NOT_CONVERT_IMG_ERROR)
        return
      }
      
      guard let fileURL = self.createFileURL(forImageWithExtension: fileExtension) else {
        print("Error: Could not create file URL")
        self.exit(withError: COULD_NOT_CREATE_FILE_URL_ERROR)
        return
      }
      
      do {
        try finalImageData.write(to: fileURL)
        url = fileURL
        print("Successfully saved UIImage to: \(fileURL.path)")
      } catch {
        print("Error writing image data: \(error.localizedDescription)")
        self.exit(withError: COULD_NOT_SAVE_FILE_ERROR)
        return
      }
    } else if let imageURL = data as? URL {
      print("Processing image URL: \(imageURL.path)")
      
      // Verify the file exists
      if !FileManager.default.fileExists(atPath: imageURL.path) {
        print("Warning: Image file does not exist at path: \(imageURL.path)")
        self.exit(withError: COULD_NOT_FIND_IMG_ERROR)
        return
      }
      
      url = imageURL
    } else {
      print("Error: Unexpected image data type: \(type(of: data))")
      self.exit(withError: COULD_NOT_FIND_IMG_ERROR)
      return
    }
    
    self.processFileURL(url, semaphore)
  }
  
  private func handleFileData(_ data: Any?, _ semaphore: DispatchSemaphore) {
    print("Handling file data of type: \(type(of: data))")
    
    guard let data = data else {
      print("Error: File data is nil")
      self.exit(withError: COULD_NOT_FIND_IMG_ERROR)
      return
    }
    
    var url: URL?
    
    if let providedURL = data as? URL {
      print("Processing file URL: \(providedURL.path)")
      
      // Verify the file exists
      if !FileManager.default.fileExists(atPath: providedURL.path) {
        print("Warning: File does not exist at path: \(providedURL.path)")
      }
      
      url = providedURL
    } else {
      print("Error: Expected URL but got: \(type(of: data))")
      self.exit(withError: COULD_NOT_FIND_IMG_ERROR)
      return
    }
    
    self.processFileURL(url, semaphore)
  }
  
  private func processFileURL(_ url: URL?, _ semaphore: DispatchSemaphore) {
    guard let url = url, let hostAppId = self.hostAppId else {
      self.exit(withError: NO_INFO_PLIST_INDENTIFIER_ERROR)
      return
    }
    
    guard let groupFileManagerContainer = FileManager.default
      .containerURL(forSecurityApplicationGroupIdentifier: "group.\(hostAppId)")
    else {
      self.exit(withError: NO_APP_GROUP_ERROR)
      return
    }
    
    let mimeType = url.extractMimeType()
    let fileExtension = url.pathExtension
    let fileName = UUID().uuidString
    let filePath = groupFileManagerContainer.appendingPathComponent("\(fileName).\(fileExtension)")
    
    guard self.moveFileToDisk(from: url, to: filePath) else {
      self.exit(withError: COULD_NOT_SAVE_FILE_ERROR)
      return
    }
    
    self.sharedItems.append([DATA_KEY: filePath.absoluteString, MIME_TYPE_KEY: mimeType])
    semaphore.signal()
  }

  func moveFileToDisk(from srcUrl: URL, to destUrl: URL) -> Bool {
    do {
      if FileManager.default.fileExists(atPath: destUrl.path) {
        try FileManager.default.removeItem(at: destUrl)
      }
      try FileManager.default.copyItem(at: srcUrl, to: destUrl)
    } catch (let error) {
      print("Could not save file from \(srcUrl) to \(destUrl): \(error)")
      return false
    }
    
    return true
  }
  
  func exit(withError error: String) {
    print("Error: \(error)")
    cancelRequest()
  }
  
  internal func openHostApp() {
    guard let urlScheme = self.hostAppUrlScheme else {
      exit(withError: NO_INFO_PLIST_URL_SCHEME_ERROR)
      return
    }
    
    guard let url = URL(string: urlScheme) else {
      print("Error: Invalid URL scheme: \(urlScheme)")
      exit(withError: "Invalid URL scheme")
      return
    }
    
    print("Opening host app with URL: \(url)")
    
    // Method 1: Use extensionContext.open (iOS 10+) - This is the proper way for share extensions
    if #available(iOS 10.0, *) {
      print("Using extensionContext.open (recommended for share extensions)")
      self.extensionContext?.open(url) { success in
        print("extensionContext.open result: \(success)")
        if !success {
          print("extensionContext.open failed, trying responder chain fallback...")
          self.tryResponderChainOpen(url)
        }
      }
    } else {
      // iOS < 10 fallback
      print("iOS < 10: Using responder chain approach")
      self.tryResponderChainOpen(url)
    }
    
    completeRequest()
  }
  
  private func tryResponderChainOpen(_ url: URL) {
    print("Using responder chain approach (share extension compatible)")
    
    // Walk up the responder chain to find UIApplication and use the modern API
    var responder: UIResponder? = self
    
    while responder != nil {
      // Check if we found UIApplication (but don't access .shared directly)
      if let app = responder as? UIApplication {
        print("Found UIApplication in responder chain")
        
        // Use the modern open API instead of deprecated openURL:
        if #available(iOS 10.0, *) {
          print("Using modern UIApplication.open method")
          app.open(url, options: [:]) { success in
            print("Responder chain UIApplication.open result: \(success)")
          }
        } else {
          // For iOS < 10, we have to use the deprecated method
          let openURLSelector = sel_registerName("openURL:")
          if app.responds(to: openURLSelector) {
            print("Using deprecated openURL for iOS < 10")
            app.perform(openURLSelector, with: url)
          }
        }
        return
      }
      responder = responder!.next
    }
    
    print("No UIApplication found in responder chain")
    
    // Note: We intentionally do NOT use UIApplication.shared here as it's not available in extensions
    // Finding UIApplication through the responder chain is the proper way for share extensions
  }
  
  func completeRequest() {
    // Inform the host that we're done, so it un-blocks its UI. Note: Alternatively you could call super's -didSelectPost, which will similarly complete the extension context.
    extensionContext!.completeRequest(returningItems: [], completionHandler: nil)
  }
  
  func cancelRequest() {
    extensionContext!.cancelRequest(withError: NSError())
  }
  
  private func createFileURL(forImageWithExtension fileExtension: String) -> URL? {
      let fileManager = FileManager.default
      let fileName = UUID().uuidString + ".\(fileExtension)"
      
      // You can replace 'documentDirectory' with 'cachesDirectory' or a custom app directory as needed
      guard let directory = fileManager.urls(for: .documentDirectory, in: .userDomainMask).first else {
          return nil
      }
      
      return directory.appendingPathComponent(fileName)
  }

}
